import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";
import AuthProvider from "@/providers/AuthProvider";
import { GlobalContextProvider } from "@/providers/UserContext";
import { JobAwardProvider } from "@/providers/JobAwardProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <AuthProvider>
        <GlobalContextProvider>
          <body className={inter.className}>
            <Providers>{children}</Providers>
          </body>
        </GlobalContextProvider>
      </AuthProvider>
    </html >
  );
}
